=== Owen-sz/backgrounds/gnome/gnome-wp-list.dtd
<!ELEMENT wallpapers (wallpaper+)>
<!ELEMENT wallpaper (name,filename,options,author,license)>
<!ATTLIST wallpaper deleted NMTOKEN #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT options (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT license (#PCDATA)>

=== Owen-sz/backgrounds/gnome/ultramarine-wallpapers-extras.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wallpapers SYSTEM "gnome-wp-list.dtd">
<wallpapers>
    <wallpaper deleted="false">
        <name>Tortuga</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/38/tortuga-light.png</filename>
        <filename-dark>/usr/share/backgrounds/ultramarine-linux/38/tortuga-dark.png</filename-dark>
        <options>zoom</options>
        <author>Aikoyori Hoshiane</author>
    </wallpaper>
    <wallpaper deleted="false">
        <name>Ultramarine</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/ultramarine/ultramarine-light.png</filename>
        <filename-dark>/usr/share/backgrounds/ultramarine-linux/ultramarine/ultramarine-dark.png</filename-dark>
        <options>zoom</options>
        <author>Aikoyori Hoshiane</author>
    </wallpaper>
        <wallpaper deleted="false">
        <name>brown concrete building on beach during daytime</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/extras/tortuga-beach.jpg</filename>
        <options>zoom</options>
        <author>Christopher Ocean</author>
    </wallpaper>
    <wallpaper deleted="false">
        <name>Blue Ocean</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/extras/blue-ocean.jpg</filename>
        <options>zoom</options>
        <author>manu schwendener</author>
        <license>CC0</license>
    </wallpaper>
    <wallpaper deleted="false">
        <name>Silhouette of Mountain</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/extras/silhouette-of-mountain.jpg</filename>
        <options>zoom</options>
        <author>Elliott Englemann</author>
        <license>CC0</license>
    </wallpaper>
    <wallpaper deleted="false">
        <name>Star Trails</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/extra/mountain-range.jpg</filename>
        <options>zoom</options>
        <author>M. Duro Jr.</author>
        <license>CC-BY-SA 4.0</license>
    </wallpaper>
     <wallpaper deleted="false">
        <name>Blueprint</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/preview/blueprint.png</filename>
        <options>zoom</options>
        <author>Jaiden Riordan</author>
        <license>CC-BY-SA 4.0</license>
    </wallpaper>

</wallpapers>

=== Owen-sz/backgrounds/gnome/41-community-extras.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wallpapers SYSTEM "gnome-wp-list.dtd">
<wallpapers>
    <wallpaper deleted="false">
        <name>Eternal Ultramarine</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/41-community-extras/Eternal-Ultramarine-Light.png</filename>
        <filename-dark>/usr/share/backgrounds/ultramarine-linux/41-community-extras/Eternal-Ultramarine-Dark.png</filename-dark>
        <options>zoom</options>
        <author>Inderix</author>
    </wallpaper>
    <wallpaper deleted="false">
        <name>Lazuli</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/41-community-extras/Lazuli-light.png</filename>
        <filename-dark>/usr/share/backgrounds/ultramarine-linux/41-community-extras/Lazuli-dark.png</filename-dark>
        <options>zoom</options>
        <author>Inderix</author>
    </wallpaper>
    <wallpaper deleted="false">
        <name>Lumos Dawn</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/41-community-extras/Lumos-Dawn.PNG</filename>
        <options>zoom</options>
        <author>Artemis</author>
    </wallpaper>
    <wallpaper deleted="false">
        <name>Really Long Name</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/41-community-extras/Really-Long-Name.PNG</filename>
        <options>zoom</options>
        <author>Artemis</author>
    </wallpaper>
    <wallpaper deleted="false">
        <name>Wavelength</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/41-community-extras/Wavelength.PNG</filename>
        <options>zoom</options>
        <author>Its-J</author>
    </wallpaper>
    <wallpaper deleted="false">
        <name>Wavelet</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/41-community-extras/wavelet-light.PNG</filename>
        <filename-dark>/usr/share/backgrounds/ultramarine-linux/41-community-extras/wavelet-dark.PNG</filename-dark>
        <options>zoom</options>
        <author>Aulys</author>
    </wallpaper>
     <wallpaper deleted="false">
        <name>Waves Clean</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/41-community-extras/waves-clean.png</filename>
        <options>zoom</options>
        <author>libano</author>
    </wallpaper>
</wallpapers>

=== Owen-sz/backgrounds/ultramarine-wallpapers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wallpapers SYSTEM "gnome-wp-list.dtd">
<wallpapers>
    <wallpaper deleted="false">
        <name>Ultramarine Linux</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/default/ultramarine-light.png</filename>
        <filename-dark>/usr/share/backgrounds/ultramarine-linux/default/ultramarine-dark.png</filename-dark>
        <options>zoom</options>
        <shade_type>solid</shade_type>
        <pcolor>#3071AE</pcolor>
        <scolor>#000000</scolor>
        <author>Aikoyori Hoshihane</author>
    </wallpaper>
    <wallpaper deleted="false">
        <name>Blue Ocean</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/blue-ocean.jpg</filename>
        <options>zoom</options>
        <author>manu schwendener</author>
        <license>CC0</license>
    </wallpaper>
    <wallpaper deleted="false">
        <name>Silhouette of Mountain</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/silhouette-of-mountain.jpg</filename>
        <options>zoom</options>
        <author>Elliott Englemann</author>
        <license>CC0</license>
    </wallpaper>
    <wallpaper deleted="false">
        <name>Artwork by Ren Ran</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/by-ren-ran.jpg</filename>
        <options>zoom</options>
        <author>Ren Ran</author>
        <license>CC0</license>
    </wallpaper>
    <wallpaper deleted="false">
        <name>Scenic View of Frozen Lake Against Mountain Range</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/default/default.jpg</filename>
        <options>zoom</options>
        <author>Pixabay</author>
        <license>CC0</license>
    </wallpaper>
    <wallpaper deleted="false">
        <name>Star Trails</name>
        <filename>/usr/share/backgrounds/ultramarine-linux/mountain-range.jpg</filename>
        <options>zoom</options>
        <author>M. Duro Jr.</author>
        <license>CC-BY-SA 4.0</license>
    </wallpaper>
</wallpapers>
